name: Vyjedená kuchařka
author: Jana Kazmar
url: http://vyjedenakucharka.github.io/
description: Vaření, vaření, konec tomu není ...
meta_description: Vaření, kuchařka, recepty.
motto: Vyjedená kuchařka

permalink: /:year-:month-:day-:title/
include: ['_pages']

exclude:
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - README.md
  - TODO.md
  - _config.yml
  - assets/img/README.md
  - js
  - less
  - node_modules
  - package.json
  - tools
  - resources
  - vendor

markdown: kramdown

collections:
  recepty:
    output: true
    permalink: /recepty/:path/
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
